Add Landing Page, Contact Page, and About Page and their components
Daskom-Lab/daskomweb2 pull request #7
Opened 2024-08-30 09:11 UTC by Zaidanfzn

## Overview
This pull request introduces several new in-page features and components as an initial look on the website later. These changes include the addition of a Landing Page, a Contact Page, and an About Page, each with its own components.

## Video Overview
[Click this to see a demonstration of the home page of the website.](https://github.com/user-attachments/assets/157affe0-c42f-4f62-bab1-b61a42dd6955)

## Some Updates

### Landing Page
- **LandingNavbar Component:** A navigation bar for the homepage.
- **MainLanding Component:** The main content section of the homepage.
- **LandingSosmed Component:** A collection of official social media links for the Daskom Laboratory.
- **SocialMediaIcon Component:** A container for social media icons.
- **SocialMediaData Component:** Data for official Daskom Laboratory social media accounts.
- **Landing Footer Component:** The footer section of the homepage.

### Contact Page
- **AboutDescription Component:** A descriptive paragraph about the Daskom Laboratory.
- **Vector Component:** Illustrative vectors representing the programming environment.

### About Page
- **ContactDescription Component:** A detailed contact description for Daskom Laboratory assistants.
- **ContactData Component:** A container for assistant contact information.

### Apptest Files
- **Apptest.jsx:** Temporary placement of pages and components to demonstrate the current code structure and functionality.

## Notes
1. The `Apptest.jsx` file is used to temporarily place the created pages and components, providing an overview of the coding structure.
2. All pages are linked into the `Apptest.jsx` temporary file, and all required components and assets are linked to the appropriate paths.
3. The CSS styles for text and backgrounds adhere to the design specifications, although manual hex colors are still in use, pending customization in `tailwind.config.js`.

2024-08-30 23:22 UTC, Raphaeline requested changes, later dismissed

2024-08-30 23:22 UTC, Raphaeline commented on resources/js/Pages/PagesPraktikan/AboutPage.jsx
> +            <div className="bg-[#EBEBEB] flex mt-7 mx-auto rounded-lg shadow-xl max-w-4xl min-h-[475px] p-5">
also this `#EBEBEB`

2024-08-30 23:22 UTC, Raphaeline commented on resources/js/Components/ComponentsPraktikans/LandingFooter.jsx
> +        <footer className='fixed left-0 right-0 mt-10 bg-[#304D30] w-full h-12'></footer>
you can add a name for `#304D30` in your `tailwind.config.js` without waiting for someone to add a customization name

2024-08-31 03:49 UTC, fakhrip commented
And also, please dont remove the `.env.example` as its important to create a template structure for the configurable environment variables @Zaidanfzn, thanks!

2025-01-05 15:15 UTC, Zaidanfzn commented on resources/js/Components/ComponentsPraktikans/LandingFooter.jsx
> +        <footer className='fixed left-0 right-0 mt-10 bg-[#304D30] w-full h-12'></footer>
Apologies for the late reply. I’ve added a name for `#304D30` in `tailwind.config.js` along with several other colors for better customization. Let me know if there’s anything else to improve. Thanks for the suggestion!

2025-01-05 15:21 UTC, Alizaaaja4 approved these changes, later dismissed
Great work, no issues from my side.

2025-01-06 08:42 UTC, DiyArc-350 commented on .env.example
> +DB_DATABASE=daskomweb2
please do note to never change this .env.example, if needed duplicate the file and rename the duplicated one to .env, since .env willl be ignored. this file may contain sensitive information if not treated properly okayy

2025-01-06 08:48 UTC, DiyArc-350 approved these changes, later dismissed
overal LGTM!

2025-01-06 10:09 UTC, Zaidanfzn commented on .env.example
> +DB_DATABASE=daskomweb2
Noted! I've adjusted .env.example to keep it clean as a template. Configs should go in .env. Thanks!

2025-01-07 14:52 UTC, Raphaeline reviewed
fix what needs to be fixed.

2025-01-07 14:52 UTC, Raphaeline commented on .env.example
> +APP_KEY=base64:jxS/GxCIP+jkDVR3kawzp/mqQsUsqB9mr6q8CaRgYTY=
be careful before you push something into repositories

2025-01-07 14:52 UTC, Raphaeline commented on routes/web.php
> +// Route::get('/dashboard', function () {
if you don't need that delete this!

2025-01-07 17:53 UTC, Zaidanfzn commented on .env.example
> +APP_KEY=base64:jxS/GxCIP+jkDVR3kawzp/mqQsUsqB9mr6q8CaRgYTY=
Thank you for the feedback, and I apologize for the mistake. I will remove the APP_KEY value and leave it empty in the .env.example file.

2025-01-07 17:59 UTC, Zaidanfzn commented on routes/web.php
> +// Route::get('/dashboard', function () {
okay, i will remove it.

2025-01-10 03:29 UTC, fakhrip submitted a review, later dismissed
looks good to me, great work guys!

2025-01-10 03:29 UTC, fakhrip commented on routes/web.php
> +// });
Please remove this later, dont let commented code pushed to github, its just a bad practice as you can already go back in the commit history to retrieve the old codes 👍

2025-01-10 05:57 UTC, Zaidanfzn commented on routes/web.php
> +// });
Thank you for the feedback! I completely understand, and I will remove the commented-out code before pushing it to GitHub. I appreciate the suggestion, and I'll make sure to keep the code clean moving forward 🙏

2025-01-10 06:17 UTC, fakhrip approved these changes

2025-01-10 06:43 UTC, merged